//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPClient.DataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataTransferObject", Namespace="http://rdl.rdlfacade.org/data#")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOAPClient.DataService.Lines))]
    public partial class DataTransferObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentifierField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Identifier {
            get {
                return this.IdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentifierField, value) != true)) {
                    this.IdentifierField = value;
                    this.RaisePropertyChanged("Identifier");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lines", Namespace="http://rdl.rdlfacade.org/data#")]
    [System.SerializableAttribute()]
    public partial class Lines : SOAPClient.DataService.DataTransferObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tpl_PipingNetworkSystemName_identifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOAPClient.DataService.Lines.TemplateSystemPipingNetworkSystemAssembly tpl_SystemPipingNetworkSystemAssemblyField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string tpl_PipingNetworkSystemName_identifier {
            get {
                return this.tpl_PipingNetworkSystemName_identifierField;
            }
            set {
                if ((object.ReferenceEquals(this.tpl_PipingNetworkSystemName_identifierField, value) != true)) {
                    this.tpl_PipingNetworkSystemName_identifierField = value;
                    this.RaisePropertyChanged("tpl_PipingNetworkSystemName_identifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SOAPClient.DataService.Lines.TemplateSystemPipingNetworkSystemAssembly tpl_SystemPipingNetworkSystemAssembly {
            get {
                return this.tpl_SystemPipingNetworkSystemAssemblyField;
            }
            set {
                if ((object.ReferenceEquals(this.tpl_SystemPipingNetworkSystemAssemblyField, value) != true)) {
                    this.tpl_SystemPipingNetworkSystemAssemblyField = value;
                    this.RaisePropertyChanged("tpl_SystemPipingNetworkSystemAssembly");
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Lines.TemplateSystemPipingNetworkSystemAssembly", Namespace="http://rdl.rdlfacade.org/data#")]
        [System.SerializableAttribute()]
        public partial class TemplateSystemPipingNetworkSystemAssembly : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private SOAPClient.DataService.Lines.TemplateSystemPipingNetworkSystemAssembly.ClassSystem hasClassOfWhole_rdl_SystemField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
            public SOAPClient.DataService.Lines.TemplateSystemPipingNetworkSystemAssembly.ClassSystem hasClassOfWhole_rdl_System {
                get {
                    return this.hasClassOfWhole_rdl_SystemField;
                }
                set {
                    if ((object.ReferenceEquals(this.hasClassOfWhole_rdl_SystemField, value) != true)) {
                        this.hasClassOfWhole_rdl_SystemField = value;
                        this.RaisePropertyChanged("hasClassOfWhole_rdl_System");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
            
            [System.Diagnostics.DebuggerStepThroughAttribute()]
            [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
            [System.Runtime.Serialization.DataContractAttribute(Name="Lines.TemplateSystemPipingNetworkSystemAssembly.ClassSystem", Namespace="http://rdl.rdlfacade.org/data#")]
            [System.SerializableAttribute()]
            public partial class ClassSystem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
                
                [System.NonSerializedAttribute()]
                private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private string IdentifierField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private string tpl_SystemName_identifierField;
                
                public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                    get {
                        return this.extensionDataField;
                    }
                    set {
                        this.extensionDataField = value;
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
                public string Identifier {
                    get {
                        return this.IdentifierField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.IdentifierField, value) != true)) {
                            this.IdentifierField = value;
                            this.RaisePropertyChanged("Identifier");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
                public string tpl_SystemName_identifier {
                    get {
                        return this.tpl_SystemName_identifierField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.tpl_SystemName_identifierField, value) != true)) {
                            this.tpl_SystemName_identifierField = value;
                            this.RaisePropertyChanged("tpl_SystemName_identifier");
                        }
                    }
                }
                
                public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
                
                protected void RaisePropertyChanged(string propertyName) {
                    System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                    if ((propertyChanged != null)) {
                        propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                    }
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ns.iringtools.org/protocol", ConfigurationName="DataService.IDataService")]
    public interface IDataService {
        
        // CODEGEN: Generating message contract since the wrapper name (DTORequest) of message DTORequest does not match the default value (GetData)
        [System.ServiceModel.OperationContractAttribute(Action="http://ns.iringtools.org/protocol/IDataService/GetData", ReplyAction="http://ns.iringtools.org/protocol/IDataService/GetDataResponse")]
        SOAPClient.DataService.DTOResponse GetData(SOAPClient.DataService.DTORequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (DTORequest) of message DTORequest does not match the default value (GetDataList)
        [System.ServiceModel.OperationContractAttribute(Action="http://ns.iringtools.org/protocol/IDataService/GetDataList", ReplyAction="http://ns.iringtools.org/protocol/IDataService/GetDataListResponse")]
        SOAPClient.DataService.DTOListResponse GetDataList(SOAPClient.DataService.DTORequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DTORequest", WrapperNamespace="http://ns.iringtools.org/protocol", IsWrapped=true)]
    public partial class DTORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ns.iringtools.org/protocol", Order=0)]
        public string applicationName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ns.iringtools.org/protocol", Order=1)]
        public string graphName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ns.iringtools.org/protocol", Order=2)]
        public string identifier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ns.iringtools.org/protocol", Order=3)]
        public string projectName;
        
        public DTORequest() {
        }
        
        public DTORequest(string applicationName, string graphName, string identifier, string projectName) {
            this.applicationName = applicationName;
            this.graphName = graphName;
            this.identifier = identifier;
            this.projectName = projectName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DTOResponse", WrapperNamespace="http://ns.iringtools.org/protocol", IsWrapped=true)]
    public partial class DTOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ns.iringtools.org/protocol", Order=0)]
        public SOAPClient.DataService.DataTransferObject dto;
        
        public DTOResponse() {
        }
        
        public DTOResponse(SOAPClient.DataService.DataTransferObject dto) {
            this.dto = dto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DTOListResponse", WrapperNamespace="http://ns.iringtools.org/protocol", IsWrapped=true)]
    public partial class DTOListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ns.iringtools.org/protocol", Order=0)]
        public System.Collections.Generic.List<SOAPClient.DataService.DataTransferObject> dtoList;
        
        public DTOListResponse() {
        }
        
        public DTOListResponse(System.Collections.Generic.List<SOAPClient.DataService.DataTransferObject> dtoList) {
            this.dtoList = dtoList;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IDataServiceChannel : SOAPClient.DataService.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<SOAPClient.DataService.IDataService>, SOAPClient.DataService.IDataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPClient.DataService.DTOResponse SOAPClient.DataService.IDataService.GetData(SOAPClient.DataService.DTORequest request) {
            return base.Channel.GetData(request);
        }
        
        public SOAPClient.DataService.DataTransferObject GetData(string applicationName, string graphName, string identifier, string projectName) {
            SOAPClient.DataService.DTORequest inValue = new SOAPClient.DataService.DTORequest();
            inValue.applicationName = applicationName;
            inValue.graphName = graphName;
            inValue.identifier = identifier;
            inValue.projectName = projectName;
            SOAPClient.DataService.DTOResponse retVal = ((SOAPClient.DataService.IDataService)(this)).GetData(inValue);
            return retVal.dto;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPClient.DataService.DTOListResponse SOAPClient.DataService.IDataService.GetDataList(SOAPClient.DataService.DTORequest request) {
            return base.Channel.GetDataList(request);
        }
        
        public System.Collections.Generic.List<SOAPClient.DataService.DataTransferObject> GetDataList(string applicationName, string graphName, string identifier, string projectName) {
            SOAPClient.DataService.DTORequest inValue = new SOAPClient.DataService.DTORequest();
            inValue.applicationName = applicationName;
            inValue.graphName = graphName;
            inValue.identifier = identifier;
            inValue.projectName = projectName;
            SOAPClient.DataService.DTOListResponse retVal = ((SOAPClient.DataService.IDataService)(this)).GetDataList(inValue);
            return retVal.dtoList;
        }
    }
}
