//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.ServiceModel;
using System.ServiceModel.Web;

namespace org.iringtools.adapter
{
  public partial interface IDataService
  {
    [OperationContract]
    [ServiceKnownType(typeof(org.iringtools.adapter.proj_CrackingComplex.SPPID.EQUIPMENT))]
    [ServiceKnownType(typeof(org.iringtools.adapter.proj_CrackingComplex.SPPID.INSTRUMENT))]
    [ServiceKnownType(typeof(org.iringtools.adapter.proj_CrackingComplex.SPPID.LINE))]
    [ServiceKnownType(typeof(org.iringtools.adapter.proj_CrackingComplex.SPPID.PipingComp))]
    DTOListResponse GetDataList(DTORequest request);
    
    [OperationContract]
    [ServiceKnownType(typeof(org.iringtools.adapter.proj_CrackingComplex.SPPID.EQUIPMENT))]
    [ServiceKnownType(typeof(org.iringtools.adapter.proj_CrackingComplex.SPPID.INSTRUMENT))]
    [ServiceKnownType(typeof(org.iringtools.adapter.proj_CrackingComplex.SPPID.LINE))]
    [ServiceKnownType(typeof(org.iringtools.adapter.proj_CrackingComplex.SPPID.PipingComp))]
    DTOResponse GetData(DTORequest request);
  }
}
