//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.22 at 11:23:05 PM EDT 
//


package org.iringtools.adapter.dto;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.iringtools.adapter.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.iringtools.adapter.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ClassObject }
     * 
     */
    public ClassObject createClassObject() {
        return new ClassObject();
    }

    /**
     * Create an instance of {@link ClassObject.TemplateObjects }
     * 
     */
    public ClassObject.TemplateObjects createClassObjectTemplateObjects() {
        return new ClassObject.TemplateObjects();
    }

    /**
     * Create an instance of {@link RoleObject }
     * 
     */
    public RoleObject createRoleObject() {
        return new RoleObject();
    }

    /**
     * Create an instance of {@link TemplateObject.RoleObjects }
     * 
     */
    public TemplateObject.RoleObjects createTemplateObjectRoleObjects() {
        return new TemplateObject.RoleObjects();
    }

    /**
     * Create an instance of {@link DataTransferObject.ClassObjects }
     * 
     */
    public DataTransferObject.ClassObjects createDataTransferObjectClassObjects() {
        return new DataTransferObject.ClassObjects();
    }

    /**
     * Create an instance of {@link DataTransferObject }
     * 
     */
    public DataTransferObject createDataTransferObject() {
        return new DataTransferObject();
    }

    /**
     * Create an instance of {@link DataTransferObjects }
     * 
     */
    public DataTransferObjects createDataTransferObjects() {
        return new DataTransferObjects();
    }

    /**
     * Create an instance of {@link TemplateObject }
     * 
     */
    public TemplateObject createTemplateObject() {
        return new TemplateObject();
    }

}
