

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by IDataService.tt.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ServiceModel;
using System.ServiceModel.Web;
using org.iringtools.adapter;

namespace org.iringtools.adapter 
{
	public partial interface IAdapterService
	{
		[XmlSerializerFormat]
		[OperationContract]
		[ServiceKnownType(typeof(org.iringtools.adapter.Valves))]		
		[ServiceKnownType(typeof(org.iringtools.adapter.Instruments))]		
		[ServiceKnownType(typeof(org.iringtools.adapter.Vessels))]		
		[ServiceKnownType(typeof(org.iringtools.adapter.Lines))]		
		[WebGet(UriTemplate = "/{graphName}/{identifier}")]
		Envelope Get(string graphName, string identifier);
		
		[XmlSerializerFormat]
		[OperationContract]
		[ServiceKnownType(typeof(org.iringtools.adapter.Valves))]		
		[ServiceKnownType(typeof(org.iringtools.adapter.Instruments))]		
		[ServiceKnownType(typeof(org.iringtools.adapter.Vessels))]		
		[ServiceKnownType(typeof(org.iringtools.adapter.Lines))]		
		[WebGet(UriTemplate = "/{graphName}")]
		Envelope GetList(string graphName);
	}
}

