//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3521
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRingFramework.Tests.Test {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Test.IReferenceDataService")]
    public interface IReferenceDataService {
        
        // CODEGEN: Parameter 'GetRepositoriesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReferenceDataService/GetRepositories", ReplyAction="http://tempuri.org/IReferenceDataService/GetRepositoriesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        IRingFramework.Tests.Test.GetRepositoriesResponse GetRepositories(IRingFramework.Tests.Test.GetRepositoriesRequest request);
        
        // CODEGEN: Parameter 'SearchResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReferenceDataService/Search", ReplyAction="http://tempuri.org/IReferenceDataService/SearchResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        IRingFramework.Tests.Test.SearchResponse Search(IRingFramework.Tests.Test.SearchRequest request);
        
        // CODEGEN: Parameter 'SearchResetResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReferenceDataService/SearchReset", ReplyAction="http://tempuri.org/IReferenceDataService/SearchResetResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        IRingFramework.Tests.Test.SearchResetResponse SearchReset(IRingFramework.Tests.Test.SearchResetRequest request);
        
        // CODEGEN: Parameter 'SearchPageResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReferenceDataService/SearchPage", ReplyAction="http://tempuri.org/IReferenceDataService/SearchPageResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        IRingFramework.Tests.Test.SearchPageResponse SearchPage(IRingFramework.Tests.Test.SearchPageRequest request);
        
        // CODEGEN: Parameter 'SearchPageResetResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReferenceDataService/SearchPageReset", ReplyAction="http://tempuri.org/IReferenceDataService/SearchPageResetResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        IRingFramework.Tests.Test.SearchPageResetResponse SearchPageReset(IRingFramework.Tests.Test.SearchPageResetRequest request);
        
        // CODEGEN: Parameter 'FindResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReferenceDataService/Find", ReplyAction="http://tempuri.org/IReferenceDataService/FindResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        IRingFramework.Tests.Test.FindResponse Find(IRingFramework.Tests.Test.FindRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReferenceDataService/GetClass", ReplyAction="http://tempuri.org/IReferenceDataService/GetClassResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        IRingFramework.Tests.Test.QMXF GetClass(string id);
        
        // CODEGEN: Parameter 'GetSubClassesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReferenceDataService/GetSubClasses", ReplyAction="http://tempuri.org/IReferenceDataService/GetSubClassesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        IRingFramework.Tests.Test.GetSubClassesResponse GetSubClasses(IRingFramework.Tests.Test.GetSubClassesRequest request);
        
        // CODEGEN: Parameter 'GetClassRelationshipsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReferenceDataService/GetClassRelationships", ReplyAction="http://tempuri.org/IReferenceDataService/GetClassRelationshipsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        IRingFramework.Tests.Test.GetClassRelationshipsResponse GetClassRelationships(IRingFramework.Tests.Test.GetClassRelationshipsRequest request);
        
        // CODEGEN: Parameter 'GetClassPropertiesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReferenceDataService/GetClassProperties", ReplyAction="http://tempuri.org/IReferenceDataService/GetClassPropertiesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        IRingFramework.Tests.Test.GetClassPropertiesResponse GetClassProperties(IRingFramework.Tests.Test.GetClassPropertiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReferenceDataService/GetTemplate", ReplyAction="http://tempuri.org/IReferenceDataService/GetTemplateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        IRingFramework.Tests.Test.QMXF GetTemplate(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReferenceDataService/PostTemplate", ReplyAction="http://tempuri.org/IReferenceDataService/PostTemplateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string[] PostTemplate(IRingFramework.Tests.Test.QMXF template);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReferenceDataService/PostClass", ReplyAction="http://tempuri.org/IReferenceDataService/PostClassResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string[] PostClass(IRingFramework.Tests.Test.QMXF @class);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3521")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class Repository : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string encryptedCredentialsField;
        
        private bool isReadOnlyField;
        
        private bool isReadOnlyFieldSpecified;
        
        private string nameField;
        
        private string uriField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string encryptedCredentials {
            get {
                return this.encryptedCredentialsField;
            }
            set {
                this.encryptedCredentialsField = value;
                this.RaisePropertyChanged("encryptedCredentials");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool isReadOnly {
            get {
                return this.isReadOnlyField;
            }
            set {
                this.isReadOnlyField = value;
                this.RaisePropertyChanged("isReadOnly");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isReadOnlySpecified {
            get {
                return this.isReadOnlyFieldSpecified;
            }
            set {
                this.isReadOnlyFieldSpecified = value;
                this.RaisePropertyChanged("isReadOnlySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
                this.RaisePropertyChanged("uri");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3521")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.ids-adi.org/qxf/model#")]
    public partial class LicenseText : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string langField;
        
        private string formalField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
                this.RaisePropertyChanged("lang");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string formal {
            get {
                return this.formalField;
            }
            set {
                this.formalField = value;
                this.RaisePropertyChanged("formal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3521")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.ids-adi.org/qxf/model#")]
    public partial class LicenseTerms : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LicenseText[] licensetextField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("license-text", Order=0)]
        public LicenseText[] licensetext {
            get {
                return this.licensetextField;
            }
            set {
                this.licensetextField = value;
                this.RaisePropertyChanged("licensetext");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3521")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.ids-adi.org/qxf/model#")]
    public partial class Specialization : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string referenceField;
        
        private string labelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
                this.RaisePropertyChanged("reference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
                this.RaisePropertyChanged("label");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3521")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.ids-adi.org/qxf/model#")]
    public partial class Classification : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string referenceField;
        
        private string labelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
                this.RaisePropertyChanged("reference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
                this.RaisePropertyChanged("label");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3521")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.ids-adi.org/qxf/model#")]
    public partial class EntityType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string referenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
                this.RaisePropertyChanged("reference");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3521")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.ids-adi.org/qxf/model#")]
    public partial class ClassDefinition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EntityType entitytypeField;
        
        private Classification[] classificationField;
        
        private Specialization[] specializationField;
        
        private SuggestedDesignation[] suggesteddesignationField;
        
        private Designation designationField;
        
        private Name[] nameField;
        
        private Description[] descriptionField;
        
        private TextualDefinition[] textualdefinitionField;
        
        private Status[] statusField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entity-type", Order=0)]
        public EntityType entitytype {
            get {
                return this.entitytypeField;
            }
            set {
                this.entitytypeField = value;
                this.RaisePropertyChanged("entitytype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("classification", Order=1)]
        public Classification[] classification {
            get {
                return this.classificationField;
            }
            set {
                this.classificationField = value;
                this.RaisePropertyChanged("classification");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("specialization", Order=2)]
        public Specialization[] specialization {
            get {
                return this.specializationField;
            }
            set {
                this.specializationField = value;
                this.RaisePropertyChanged("specialization");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("suggested-designation", Order=3)]
        public SuggestedDesignation[] suggesteddesignation {
            get {
                return this.suggesteddesignationField;
            }
            set {
                this.suggesteddesignationField = value;
                this.RaisePropertyChanged("suggesteddesignation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Designation designation {
            get {
                return this.designationField;
            }
            set {
                this.designationField = value;
                this.RaisePropertyChanged("designation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("name", Order=5)]
        public Name[] name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("description", Order=6)]
        public Description[] description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("textual-definition", Order=7)]
        public TextualDefinition[] textualdefinition {
            get {
                return this.textualdefinitionField;
            }
            set {
                this.textualdefinitionField = value;
                this.RaisePropertyChanged("textualdefinition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("status", Order=8)]
        public Status[] status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3521")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.ids-adi.org/qxf/model#")]
    public partial class SuggestedDesignation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3521")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.ids-adi.org/qxf/model#")]
    public partial class Designation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3521")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.ids-adi.org/qxf/model#")]
    public partial class Name : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string langField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
                this.RaisePropertyChanged("lang");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3521")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.ids-adi.org/qxf/model#")]
    public partial class Description : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string langField;
        
        private string contentTypeField;
        
        private string parseTypeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
                this.RaisePropertyChanged("lang");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string contentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
                this.RaisePropertyChanged("contentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string parseType {
            get {
                return this.parseTypeField;
            }
            set {
                this.parseTypeField = value;
                this.RaisePropertyChanged("parseType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3521")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.ids-adi.org/qxf/model#")]
    public partial class TextualDefinition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string langField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
                this.RaisePropertyChanged("lang");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3521")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.ids-adi.org/qxf/model#")]
    public partial class Status : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string authorityField;
        
        private string classField;
        
        private string fromField;
        
        private string toField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
                this.RaisePropertyChanged("authority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
                this.RaisePropertyChanged("class");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string from {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
                this.RaisePropertyChanged("from");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
                this.RaisePropertyChanged("to");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3521")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.ids-adi.org/qxf/model#")]
    public partial class Value : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string langField;
        
        private string referenceField;
        
        private string asField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
                this.RaisePropertyChanged("lang");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
                this.RaisePropertyChanged("reference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string As {
            get {
                return this.asField;
            }
            set {
                this.asField = value;
                this.RaisePropertyChanged("As");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3521")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.ids-adi.org/qxf/model#")]
    public partial class RoleQualification : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Name[] nameField;
        
        private Value valueField;
        
        private Description[] descriptionField;
        
        private string qualifiesField;
        
        private string rangeField;
        
        private string minimumField;
        
        private string maximumField;
        
        private string inverseminimumField;
        
        private string inversemaximumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("name", Order=0)]
        public Name[] name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Value value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("description", Order=2)]
        public Description[] description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string qualifies {
            get {
                return this.qualifiesField;
            }
            set {
                this.qualifiesField = value;
                this.RaisePropertyChanged("qualifies");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string range {
            get {
                return this.rangeField;
            }
            set {
                this.rangeField = value;
                this.RaisePropertyChanged("range");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string minimum {
            get {
                return this.minimumField;
            }
            set {
                this.minimumField = value;
                this.RaisePropertyChanged("minimum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string maximum {
            get {
                return this.maximumField;
            }
            set {
                this.maximumField = value;
                this.RaisePropertyChanged("maximum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("inverse-minimum")]
        public string inverseminimum {
            get {
                return this.inverseminimumField;
            }
            set {
                this.inverseminimumField = value;
                this.RaisePropertyChanged("inverseminimum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("inverse-maximum")]
        public string inversemaximum {
            get {
                return this.inversemaximumField;
            }
            set {
                this.inversemaximumField = value;
                this.RaisePropertyChanged("inversemaximum");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3521")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.ids-adi.org/qxf/model#")]
    public partial class TemplateQualification : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SuggestedDesignation[] suggesteddesignationField;
        
        private Designation[] designationField;
        
        private Name[] nameField;
        
        private Description[] descriptionField;
        
        private TextualDefinition[] textualdefinitionField;
        
        private Status[] statusField;
        
        private RoleQualification[] rolequalificationField;
        
        private string idField;
        
        private string qualifiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("suggested-designation", Order=0)]
        public SuggestedDesignation[] suggesteddesignation {
            get {
                return this.suggesteddesignationField;
            }
            set {
                this.suggesteddesignationField = value;
                this.RaisePropertyChanged("suggesteddesignation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("designation", Order=1)]
        public Designation[] designation {
            get {
                return this.designationField;
            }
            set {
                this.designationField = value;
                this.RaisePropertyChanged("designation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("name", Order=2)]
        public Name[] name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("description", Order=3)]
        public Description[] description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("textual-definition", Order=4)]
        public TextualDefinition[] textualdefinition {
            get {
                return this.textualdefinitionField;
            }
            set {
                this.textualdefinitionField = value;
                this.RaisePropertyChanged("textualdefinition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("status", Order=5)]
        public Status[] status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("role-qualification", Order=6)]
        public RoleQualification[] rolequalification {
            get {
                return this.rolequalificationField;
            }
            set {
                this.rolequalificationField = value;
                this.RaisePropertyChanged("rolequalification");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string qualifies {
            get {
                return this.qualifiesField;
            }
            set {
                this.qualifiesField = value;
                this.RaisePropertyChanged("qualifies");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3521")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.ids-adi.org/qxf/model#")]
    public partial class RoleDefinition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Name[] nameField;
        
        private SuggestedDesignation[] suggesteddesignationField;
        
        private Designation designationField;
        
        private Description descriptionField;
        
        private string idField;
        
        private string rangeField;
        
        private string minimumField;
        
        private string maximumField;
        
        private string inverseminimumField;
        
        private string inversemaximumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("name", Order=0)]
        public Name[] name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("suggested-designation", Order=1)]
        public SuggestedDesignation[] suggesteddesignation {
            get {
                return this.suggesteddesignationField;
            }
            set {
                this.suggesteddesignationField = value;
                this.RaisePropertyChanged("suggesteddesignation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Designation designation {
            get {
                return this.designationField;
            }
            set {
                this.designationField = value;
                this.RaisePropertyChanged("designation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Description description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string range {
            get {
                return this.rangeField;
            }
            set {
                this.rangeField = value;
                this.RaisePropertyChanged("range");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string minimum {
            get {
                return this.minimumField;
            }
            set {
                this.minimumField = value;
                this.RaisePropertyChanged("minimum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string maximum {
            get {
                return this.maximumField;
            }
            set {
                this.maximumField = value;
                this.RaisePropertyChanged("maximum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("inverse-minimum")]
        public string inverseminimum {
            get {
                return this.inverseminimumField;
            }
            set {
                this.inverseminimumField = value;
                this.RaisePropertyChanged("inverseminimum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("inverse-maximum")]
        public string inversemaximum {
            get {
                return this.inversemaximumField;
            }
            set {
                this.inversemaximumField = value;
                this.RaisePropertyChanged("inversemaximum");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3521")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.ids-adi.org/qxf/model#")]
    public partial class TemplateDefinition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SuggestedDesignation[] suggesteddesignationField;
        
        private Designation designationField;
        
        private Name[] nameField;
        
        private Description[] descriptionField;
        
        private TextualDefinition[] textualdefinitionField;
        
        private Status[] statusField;
        
        private RoleDefinition[] roledefinitionField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("suggested-designation", Order=0)]
        public SuggestedDesignation[] suggesteddesignation {
            get {
                return this.suggesteddesignationField;
            }
            set {
                this.suggesteddesignationField = value;
                this.RaisePropertyChanged("suggesteddesignation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Designation designation {
            get {
                return this.designationField;
            }
            set {
                this.designationField = value;
                this.RaisePropertyChanged("designation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("name", Order=2)]
        public Name[] name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("description", Order=3)]
        public Description[] description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("textual-definition", Order=4)]
        public TextualDefinition[] textualdefinition {
            get {
                return this.textualdefinitionField;
            }
            set {
                this.textualdefinitionField = value;
                this.RaisePropertyChanged("textualdefinition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("status", Order=5)]
        public Status[] status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("role-definition", Order=6)]
        public RoleDefinition[] roledefinition {
            get {
                return this.roledefinitionField;
            }
            set {
                this.roledefinitionField = value;
                this.RaisePropertyChanged("roledefinition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3521")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.ids-adi.org/qxf/model#")]
    public partial class QMXF : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TemplateDefinition[] templatedefinitionField;
        
        private TemplateQualification[] templatequalificationField;
        
        private ClassDefinition[] classdefinitionField;
        
        private LicenseTerms[][] licenseField;
        
        private string timestampField;
        
        private string licenserefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("template-definition", Order=0)]
        public TemplateDefinition[] templatedefinition {
            get {
                return this.templatedefinitionField;
            }
            set {
                this.templatedefinitionField = value;
                this.RaisePropertyChanged("templatedefinition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("template-qualification", Order=1)]
        public TemplateQualification[] templatequalification {
            get {
                return this.templatequalificationField;
            }
            set {
                this.templatequalificationField = value;
                this.RaisePropertyChanged("templatequalification");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("class-definition", Order=2)]
        public ClassDefinition[] classdefinition {
            get {
                return this.classdefinitionField;
            }
            set {
                this.classdefinitionField = value;
                this.RaisePropertyChanged("classdefinition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("license-terms", typeof(LicenseTerms), IsNullable=false)]
        public LicenseTerms[][] license {
            get {
                return this.licenseField;
            }
            set {
                this.licenseField = value;
                this.RaisePropertyChanged("license");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("license-ref")]
        public string licenseref {
            get {
                return this.licenserefField;
            }
            set {
                this.licenserefField = value;
                this.RaisePropertyChanged("licenseref");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3521")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class Entity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string labelField;
        
        private string repositoryField;
        
        private string uriField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
                this.RaisePropertyChanged("label");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string repository {
            get {
                return this.repositoryField;
            }
            set {
                this.repositoryField = value;
                this.RaisePropertyChanged("repository");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
                this.RaisePropertyChanged("uri");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRepositories", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRepositoriesRequest {
        
        public GetRepositoriesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRepositoriesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRepositoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
        public Repository[] GetRepositoriesResult;
        
        public GetRepositoriesResponse() {
        }
        
        public GetRepositoriesResponse(Repository[] GetRepositoriesResult) {
            this.GetRepositoriesResult = GetRepositoriesResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3521")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class EntitiesKeyValueOfstringEntitylLTIrbuF : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private Entity valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public Entity Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Search", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string query;
        
        public SearchRequest() {
        }
        
        public SearchRequest(string query) {
            this.query = query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringEntitylLTIrbuF", Namespace="http://schemas.datacontract.org/2004/07/", IsNullable=false)]
        public EntitiesKeyValueOfstringEntitylLTIrbuF[] SearchResult;
        
        public SearchResponse() {
        }
        
        public SearchResponse(EntitiesKeyValueOfstringEntitylLTIrbuF[] SearchResult) {
            this.SearchResult = SearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchReset", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchResetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string query;
        
        public SearchResetRequest() {
        }
        
        public SearchResetRequest(string query) {
            this.query = query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchResetResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchResetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringEntitylLTIrbuF", Namespace="http://schemas.datacontract.org/2004/07/", IsNullable=false)]
        public EntitiesKeyValueOfstringEntitylLTIrbuF[] SearchResetResult;
        
        public SearchResetResponse() {
        }
        
        public SearchResetResponse(EntitiesKeyValueOfstringEntitylLTIrbuF[] SearchResetResult) {
            this.SearchResetResult = SearchResetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchPage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchPageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string query;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string page;
        
        public SearchPageRequest() {
        }
        
        public SearchPageRequest(string query, string page) {
            this.query = query;
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchPageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchPageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringEntitylLTIrbuF", Namespace="http://schemas.datacontract.org/2004/07/", IsNullable=false)]
        public EntitiesKeyValueOfstringEntitylLTIrbuF[] SearchPageResult;
        
        public SearchPageResponse() {
        }
        
        public SearchPageResponse(EntitiesKeyValueOfstringEntitylLTIrbuF[] SearchPageResult) {
            this.SearchPageResult = SearchPageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchPageReset", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchPageResetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string query;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string page;
        
        public SearchPageResetRequest() {
        }
        
        public SearchPageResetRequest(string query, string page) {
            this.query = query;
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchPageResetResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchPageResetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringEntitylLTIrbuF", Namespace="http://schemas.datacontract.org/2004/07/", IsNullable=false)]
        public EntitiesKeyValueOfstringEntitylLTIrbuF[] SearchPageResetResult;
        
        public SearchPageResetResponse() {
        }
        
        public SearchPageResetResponse(EntitiesKeyValueOfstringEntitylLTIrbuF[] SearchPageResetResult) {
            this.SearchPageResetResult = SearchPageResetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Find", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string query;
        
        public FindRequest() {
        }
        
        public FindRequest(string query) {
            this.query = query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
        public Entity[] FindResult;
        
        public FindResponse() {
        }
        
        public FindResponse(Entity[] FindResult) {
            this.FindResult = FindResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSubClasses", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSubClassesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string id;
        
        public GetSubClassesRequest() {
        }
        
        public GetSubClassesRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSubClassesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSubClassesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
        public Entity[] GetSubClassesResult;
        
        public GetSubClassesResponse() {
        }
        
        public GetSubClassesResponse(Entity[] GetSubClassesResult) {
            this.GetSubClassesResult = GetSubClassesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClassRelationships", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetClassRelationshipsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string id;
        
        public GetClassRelationshipsRequest() {
        }
        
        public GetClassRelationshipsRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClassRelationshipsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetClassRelationshipsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
        public Entity[] GetClassRelationshipsResult;
        
        public GetClassRelationshipsResponse() {
        }
        
        public GetClassRelationshipsResponse(Entity[] GetClassRelationshipsResult) {
            this.GetClassRelationshipsResult = GetClassRelationshipsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClassProperties", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetClassPropertiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string id;
        
        public GetClassPropertiesRequest() {
        }
        
        public GetClassPropertiesRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClassPropertiesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetClassPropertiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
        public Entity[] GetClassPropertiesResult;
        
        public GetClassPropertiesResponse() {
        }
        
        public GetClassPropertiesResponse(Entity[] GetClassPropertiesResult) {
            this.GetClassPropertiesResult = GetClassPropertiesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IReferenceDataServiceChannel : IRingFramework.Tests.Test.IReferenceDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ReferenceDataServiceClient : System.ServiceModel.ClientBase<IRingFramework.Tests.Test.IReferenceDataService>, IRingFramework.Tests.Test.IReferenceDataService {
        
        public ReferenceDataServiceClient() {
        }
        
        public ReferenceDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReferenceDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReferenceDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReferenceDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IRingFramework.Tests.Test.GetRepositoriesResponse IRingFramework.Tests.Test.IReferenceDataService.GetRepositories(IRingFramework.Tests.Test.GetRepositoriesRequest request) {
            return base.Channel.GetRepositories(request);
        }
        
        public Repository[] GetRepositories() {
            IRingFramework.Tests.Test.GetRepositoriesRequest inValue = new IRingFramework.Tests.Test.GetRepositoriesRequest();
            IRingFramework.Tests.Test.GetRepositoriesResponse retVal = ((IRingFramework.Tests.Test.IReferenceDataService)(this)).GetRepositories(inValue);
            return retVal.GetRepositoriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IRingFramework.Tests.Test.SearchResponse IRingFramework.Tests.Test.IReferenceDataService.Search(IRingFramework.Tests.Test.SearchRequest request) {
            return base.Channel.Search(request);
        }
        
        public EntitiesKeyValueOfstringEntitylLTIrbuF[] Search(string query) {
            IRingFramework.Tests.Test.SearchRequest inValue = new IRingFramework.Tests.Test.SearchRequest();
            inValue.query = query;
            IRingFramework.Tests.Test.SearchResponse retVal = ((IRingFramework.Tests.Test.IReferenceDataService)(this)).Search(inValue);
            return retVal.SearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IRingFramework.Tests.Test.SearchResetResponse IRingFramework.Tests.Test.IReferenceDataService.SearchReset(IRingFramework.Tests.Test.SearchResetRequest request) {
            return base.Channel.SearchReset(request);
        }
        
        public EntitiesKeyValueOfstringEntitylLTIrbuF[] SearchReset(string query) {
            IRingFramework.Tests.Test.SearchResetRequest inValue = new IRingFramework.Tests.Test.SearchResetRequest();
            inValue.query = query;
            IRingFramework.Tests.Test.SearchResetResponse retVal = ((IRingFramework.Tests.Test.IReferenceDataService)(this)).SearchReset(inValue);
            return retVal.SearchResetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IRingFramework.Tests.Test.SearchPageResponse IRingFramework.Tests.Test.IReferenceDataService.SearchPage(IRingFramework.Tests.Test.SearchPageRequest request) {
            return base.Channel.SearchPage(request);
        }
        
        public EntitiesKeyValueOfstringEntitylLTIrbuF[] SearchPage(string query, string page) {
            IRingFramework.Tests.Test.SearchPageRequest inValue = new IRingFramework.Tests.Test.SearchPageRequest();
            inValue.query = query;
            inValue.page = page;
            IRingFramework.Tests.Test.SearchPageResponse retVal = ((IRingFramework.Tests.Test.IReferenceDataService)(this)).SearchPage(inValue);
            return retVal.SearchPageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IRingFramework.Tests.Test.SearchPageResetResponse IRingFramework.Tests.Test.IReferenceDataService.SearchPageReset(IRingFramework.Tests.Test.SearchPageResetRequest request) {
            return base.Channel.SearchPageReset(request);
        }
        
        public EntitiesKeyValueOfstringEntitylLTIrbuF[] SearchPageReset(string query, string page) {
            IRingFramework.Tests.Test.SearchPageResetRequest inValue = new IRingFramework.Tests.Test.SearchPageResetRequest();
            inValue.query = query;
            inValue.page = page;
            IRingFramework.Tests.Test.SearchPageResetResponse retVal = ((IRingFramework.Tests.Test.IReferenceDataService)(this)).SearchPageReset(inValue);
            return retVal.SearchPageResetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IRingFramework.Tests.Test.FindResponse IRingFramework.Tests.Test.IReferenceDataService.Find(IRingFramework.Tests.Test.FindRequest request) {
            return base.Channel.Find(request);
        }
        
        public Entity[] Find(string query) {
            IRingFramework.Tests.Test.FindRequest inValue = new IRingFramework.Tests.Test.FindRequest();
            inValue.query = query;
            IRingFramework.Tests.Test.FindResponse retVal = ((IRingFramework.Tests.Test.IReferenceDataService)(this)).Find(inValue);
            return retVal.FindResult;
        }
        
        public IRingFramework.Tests.Test.QMXF GetClass(string id) {
            return base.Channel.GetClass(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IRingFramework.Tests.Test.GetSubClassesResponse IRingFramework.Tests.Test.IReferenceDataService.GetSubClasses(IRingFramework.Tests.Test.GetSubClassesRequest request) {
            return base.Channel.GetSubClasses(request);
        }
        
        public Entity[] GetSubClasses(string id) {
            IRingFramework.Tests.Test.GetSubClassesRequest inValue = new IRingFramework.Tests.Test.GetSubClassesRequest();
            inValue.id = id;
            IRingFramework.Tests.Test.GetSubClassesResponse retVal = ((IRingFramework.Tests.Test.IReferenceDataService)(this)).GetSubClasses(inValue);
            return retVal.GetSubClassesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IRingFramework.Tests.Test.GetClassRelationshipsResponse IRingFramework.Tests.Test.IReferenceDataService.GetClassRelationships(IRingFramework.Tests.Test.GetClassRelationshipsRequest request) {
            return base.Channel.GetClassRelationships(request);
        }
        
        public Entity[] GetClassRelationships(string id) {
            IRingFramework.Tests.Test.GetClassRelationshipsRequest inValue = new IRingFramework.Tests.Test.GetClassRelationshipsRequest();
            inValue.id = id;
            IRingFramework.Tests.Test.GetClassRelationshipsResponse retVal = ((IRingFramework.Tests.Test.IReferenceDataService)(this)).GetClassRelationships(inValue);
            return retVal.GetClassRelationshipsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IRingFramework.Tests.Test.GetClassPropertiesResponse IRingFramework.Tests.Test.IReferenceDataService.GetClassProperties(IRingFramework.Tests.Test.GetClassPropertiesRequest request) {
            return base.Channel.GetClassProperties(request);
        }
        
        public Entity[] GetClassProperties(string id) {
            IRingFramework.Tests.Test.GetClassPropertiesRequest inValue = new IRingFramework.Tests.Test.GetClassPropertiesRequest();
            inValue.id = id;
            IRingFramework.Tests.Test.GetClassPropertiesResponse retVal = ((IRingFramework.Tests.Test.IReferenceDataService)(this)).GetClassProperties(inValue);
            return retVal.GetClassPropertiesResult;
        }
        
        public IRingFramework.Tests.Test.QMXF GetTemplate(string id) {
            return base.Channel.GetTemplate(id);
        }
        
        public string[] PostTemplate(IRingFramework.Tests.Test.QMXF template) {
            return base.Channel.PostTemplate(template);
        }
        
        public string[] PostClass(IRingFramework.Tests.Test.QMXF @class) {
            return base.Channel.PostClass(@class);
        }
    }
}
