USE [iring_test]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__EQUIPMENT__INSUL__08EA5793]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[EQUIPMENT] DROP CONSTRAINT [DF__EQUIPMENT__INSUL__08EA5793]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__EQUIPMENT__INSUL__09DE7BCC]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[EQUIPMENT] DROP CONSTRAINT [DF__EQUIPMENT__INSUL__09DE7BCC]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__EQUIPMENT__PRESS__0AD2A005]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[EQUIPMENT] DROP CONSTRAINT [DF__EQUIPMENT__PRESS__0AD2A005]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__EQUIPMENT__TEMP___0BC6C43E]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[EQUIPMENT] DROP CONSTRAINT [DF__EQUIPMENT__TEMP___0BC6C43E]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__EQUIPMENT__DIFF___0CBAE877]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[EQUIPMENT] DROP CONSTRAINT [DF__EQUIPMENT__DIFF___0CBAE877]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__EQUIPMENT__LENGT__0DAF0CB0]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[EQUIPMENT] DROP CONSTRAINT [DF__EQUIPMENT__LENGT__0DAF0CB0]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__EQUIPMENT__DIAME__0EA330E9]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[EQUIPMENT] DROP CONSTRAINT [DF__EQUIPMENT__DIAME__0EA330E9]
END

GO

USE [iring_test]
GO

/****** Object:  Table [dbo].[EQUIPMENT]    Script Date: 03/22/2010 16:36:00 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EQUIPMENT]') AND type in (N'U'))
DROP TABLE [dbo].[EQUIPMENT]
GO

USE [iring_test]
GO

/****** Object:  Table [dbo].[EQUIPMENT]    Script Date: 03/22/2010 16:36:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[EQUIPMENT](
	[TAGNO] [varchar](30) NOT NULL,
	[STATUS] [varchar](20) NULL,
	[PLANT] [varchar](20) NULL,
	[PLANT_AREA] [varchar](20) NULL,
	[SYSTEM] [varchar](20) NULL,
	[DESCRIPTION] [varchar](100) NULL,
	[PID] [varchar](30) NULL,
	[PID_REV] [varchar](3) NULL,
	[INSULATION_YN] [varchar](1) NULL,
	[INSULATION_THICKNESS] [decimal](6, 2) NULL,
	[INSULATION_THICKNESS_UOM] [varchar](16) NULL,
	[OP_PRESS] [decimal](6, 2) NULL,
	[DGN_PRESS] [decimal](6, 2) NULL,
	[PRESS_UOM] [varchar](16) NULL,
	[OP_TEMP] [decimal](6, 2) NULL,
	[DGN_TEMP] [decimal](6, 2) NULL,
	[TEMP_UOM] [varchar](16) NULL,
	[DIFF_PRESS] [decimal](6, 2) NULL,
	[DIFF_PRESS_UOM] [varchar](16) NULL,
	[CAPACITY] [decimal](6, 2) NULL,
	[CAPACITY_UOM] [varchar](16) NULL,
	[SG] [decimal](6, 3) NULL,
	[LENGTH] [decimal](6, 2) NULL,
	[LENGTH_UOM] [varchar](16) NULL,
	[DIAMETER] [decimal](6, 2) NULL,
	[DIAMETER_UOM] [varchar](20) NULL,
	[MATERIAL] [varchar](50) NULL,
	[MANUFACTURER] [varchar](100) NULL,
	[MODEL_NO] [varchar](100) NULL,
	[FLUID] [varchar](20) NULL,
	[TYPE] [varchar](20) NULL,
	[DRIVER_TYPE] [varchar](20) NULL,
	[REMARKS] [varchar](50) NULL,
	[DELETED] [varchar](1) NULL,
	[PREPARED_BY] [varchar](30) NULL,
	[DESIGN_STATE] [varchar](20) NULL,
	[UPDATED_BY] [varchar](30) NULL,
	[TIME_STAMP] [datetime] NULL,
	[IMPORT_SRC] [varchar](30) NULL,
	[CUSER] [varchar](30) NULL,
	CONSTRAINT "EQUIPMENT_PK" PRIMARY KEY ("TAGNO")
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[EQUIPMENT] ADD  DEFAULT ('N') FOR [INSULATION_YN]
GO

ALTER TABLE [dbo].[EQUIPMENT] ADD  DEFAULT ('mm') FOR [INSULATION_THICKNESS_UOM]
GO

ALTER TABLE [dbo].[EQUIPMENT] ADD  DEFAULT ('bar') FOR [PRESS_UOM]
GO

ALTER TABLE [dbo].[EQUIPMENT] ADD  DEFAULT ('degC') FOR [TEMP_UOM]
GO

ALTER TABLE [dbo].[EQUIPMENT] ADD  DEFAULT ('bar') FOR [DIFF_PRESS_UOM]
GO

ALTER TABLE [dbo].[EQUIPMENT] ADD  DEFAULT ('mm') FOR [LENGTH_UOM]
GO

ALTER TABLE [dbo].[EQUIPMENT] ADD  DEFAULT ('mm') FOR [DIAMETER_UOM]
GO

