IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'<<TOKEN>>')
DROP DATABASE [<<TOKEN>>]
GO

IF EXISTS (SELECT * FROM sys.syslogins WHERE name = N'<<TOKEN>>')
DROP LOGIN [<<TOKEN>>]
GO

CREATE DATABASE [<<TOKEN>>]
GO

USE [<<TOKEN>>]
GO

CREATE LOGIN [<<TOKEN>>] WITH PASSWORD = '<<TOKEN>>', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE USER [<<TOKEN>>] FOR LOGIN [<<TOKEN>>]
GO

EXEC sp_addrolemember db_owner, [<<TOKEN>>]

