/*
* File: Scripts/AM/view/directory/ViewJobsForm.js
*
* This file was generated by Sencha Architect version 2.2.2.
* http://www.sencha.com/products/architect/
*
* This file requires use of the Ext JS 4.1.x library, under independent license.
* License of Sencha Architect does not include license for Ext JS 4.1.x. For more
* details see http://www.sencha.com/license or contact license@sencha.com.
*
* This file will be auto-generated each and everytime you save your project.
*
* Do NOT hand edit this file.
*/
Ext.define('AM.view.directory.ViewJobsForm', {
    extend: 'Ext.Panel',
    alias: 'widget.viewjobsform',
    //requires: ['Ext.ux.form.SearchField'],
    node: '',
    border: 0,
    bodyPadding: 10,
    bodyStyle: 'padding:10px 5px 0',
    initComponent: function () {
        var me = this;

        me.initialConfig = Ext.apply({

        }, me.initialConfig);


        Ext.applyIf(me, {

            items: [{
                xtype: 'container',
                layout: 'hbox'

            },

                {
                    xtype: 'grid',
                    margin: '0 0 0 0',
                    alias: 'widget.viewjobsgrid',
                    store: 'JobStore',
                    autoHeight: true,
                    autoWidth: true,
                    border: 0,
                    columns: [

                      { xtype: 'gridcolumn',
                          text: 'Context Name', dataIndex: 'ContextName', width: 150, autoSizeColumn: true
                      }, { xtype: 'gridcolumn',
                          text: 'Application Name ', dataIndex: 'AppName', width: 150, autoSizeColumn: true
                      },
                      { xtype: 'gridcolumn',
                          text: 'Status', dataIndex: 'Status', width: 150, autoSizeColumn: true
                      },
                    { xtype: 'gridcolumn',
                        text: 'Last Start Time', dataIndex: 'Last_Start_DateTime', width: 150, autoSizeColumn: true
                    },
                    { xtype: 'gridcolumn',
                        text: 'Next Start Time', dataIndex: 'Next_Start_DateTime', width: 150, autoSizeColumn: true
                    },
                         { xtype: 'gridcolumn',
                             text: 'Total Records', dataIndex: 'TotalRecords'
                         }, { xtype: 'gridcolumn',
                             text: 'Cached Records', dataIndex: 'CachedRecords'
                         }

                    ],
                    listeners: {

                        itemcontextmenu: function (view, record, item, index, e) {
                            // Stop the browser getting the event 
                            e.preventDefault();
                            var permMenu = Ext.widget('jobsmenu');
                            permMenu.showAt(e.getXY());
                        }
                    },
                    width: 1000

                }
            ]
        });

        me.callParent(arguments);
    }


});