//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.23 at 04:39:42 PM EDT 
//


package org.iringtools.protocol.manifest;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Graph complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Graph">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="classTemplatesList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="classTemplates" type="{http://iringtools.org/protocol/manifest}ClassTemplates" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Graph", propOrder = {
    "name",
    "classTemplatesList"
})
public class Graph {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected Graph.ClassTemplatesList classTemplatesList;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the classTemplatesList property.
     * 
     * @return
     *     possible object is
     *     {@link Graph.ClassTemplatesList }
     *     
     */
    public Graph.ClassTemplatesList getClassTemplatesList() {
        return classTemplatesList;
    }

    /**
     * Sets the value of the classTemplatesList property.
     * 
     * @param value
     *     allowed object is
     *     {@link Graph.ClassTemplatesList }
     *     
     */
    public void setClassTemplatesList(Graph.ClassTemplatesList value) {
        this.classTemplatesList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="classTemplates" type="{http://iringtools.org/protocol/manifest}ClassTemplates" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "classTemplates"
    })
    public static class ClassTemplatesList {

        protected List<ClassTemplates> classTemplates;

        /**
         * Gets the value of the classTemplates property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the classTemplates property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getClassTemplates().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ClassTemplates }
         * 
         * 
         */
        public List<ClassTemplates> getClassTemplates() {
            if (classTemplates == null) {
                classTemplates = new ArrayList<ClassTemplates>();
            }
            return this.classTemplates;
        }

        /**
         * Sets the value of the classTemplates property.
         * 
         * @param classTemplates
         *     allowed object is
         *     {@link ClassTemplates }
         *     
         */
        public void setClassTemplates(List<ClassTemplates> classTemplates) {
            this.classTemplates = classTemplates;
        }

    }

}
