//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.10 at 03:24:31 PM GMT+05:30 
//


package org.iringtools.federation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IDGenerators complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IDGenerators">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="iDGenerator" type="{http://iringtools.org/federation}IDGenerator"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IDGenerators", propOrder = {
    "idGenerator"
})
public class IDGenerators {

    @XmlElement(name = "iDGenerator", required = true)
    protected IDGenerator idGenerator;

    /**
     * Gets the value of the idGenerator property.
     * 
     * @return
     *     possible object is
     *     {@link IDGenerator }
     *     
     */
    public IDGenerator getIDGenerator() {
        return idGenerator;
    }

    /**
     * Sets the value of the idGenerator property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDGenerator }
     *     
     */
    public void setIDGenerator(IDGenerator value) {
        this.idGenerator = value;
    }

}
