//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.ServiceModel;
using System.ServiceModel.Web;

namespace org.iringtools.adapter
{
  public partial interface IService
  {
    [OperationContract]
    [XmlSerializerFormat]
    [WebGet(UriTemplate = "/{projectName}/{applicationName}/{graphName}")]
    Envelope GetList(string projectName, string applicationName, string graphName);
    
    [OperationContract]
    [XmlSerializerFormat]
    [WebGet(UriTemplate = "/{projectName}/{applicationName}/{graphName}/{identifier}")]
    Envelope Get(string projectName, string applicationName, string graphName, string identifier);
  }
}
