/*
 * File: Scripts/AM/store/TestStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AM.store.TestStore', {
  extend: 'Ext.data.Store',
  alias: 'store.TestStore',

  requires: [
    'AM.model.VirtualPropertyModel'
  ],

  constructor: function(cfg) {
    var me = this;
    cfg = cfg || {};
    me.callParent([Ext.apply({
      autoLoad: true,
      model: 'AM.model.VirtualPropertyModel',
      storeId: 'TestStoreID',
      proxy: {
        type: 'ajax',
        url: '/scripts/sample.json',
        reader: {
          type: 'json',
          root: 'data'
        }
      }
    }, cfg)]);
  }
});