//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.04 at 02:41:25 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://iringtools.org/common/history", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.iringtools.common.history;
