//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.09 at 12:39:22 PM GMT+05:30 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://iringtools.org/repository", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.iringtools.repository;
