//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.22 at 11:23:17 PM EDT 
//


package org.iringtools.adapter.manifest;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.iringtools.adapter.manifest package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.iringtools.adapter.manifest
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Class }
     * 
     */
    public Class createClass() {
        return new Class();
    }

    /**
     * Create an instance of {@link Manifest.Graphs }
     * 
     */
    public Manifest.Graphs createManifestGraphs() {
        return new Manifest.Graphs();
    }

    /**
     * Create an instance of {@link ClassTemplatesMap.Templates }
     * 
     */
    public ClassTemplatesMap.Templates createClassTemplatesMapTemplates() {
        return new ClassTemplatesMap.Templates();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link Template }
     * 
     */
    public Template createTemplate() {
        return new Template();
    }

    /**
     * Create an instance of {@link Graph.ClassTemplatesMaps }
     * 
     */
    public Graph.ClassTemplatesMaps createGraphClassTemplatesMaps() {
        return new Graph.ClassTemplatesMaps();
    }

    /**
     * Create an instance of {@link Manifest }
     * 
     */
    public Manifest createManifest() {
        return new Manifest();
    }

    /**
     * Create an instance of {@link Template.Roles }
     * 
     */
    public Template.Roles createTemplateRoles() {
        return new Template.Roles();
    }

    /**
     * Create an instance of {@link ClassTemplatesMap }
     * 
     */
    public ClassTemplatesMap createClassTemplatesMap() {
        return new ClassTemplatesMap();
    }

    /**
     * Create an instance of {@link Graph }
     * 
     */
    public Graph createGraph() {
        return new Graph();
    }

}
