//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Globalization;
using System.Collections.Generic;
using Iesi.Collections.Generic;
using org.iringtools.library;

namespace org.iringtools.adapter.datalayer.proj_finaly.finlayApp
{
  public class EQUIPMENT2 : IDataObject
  {
    public virtual String Id { get; set; }
    public virtual String TAG
    {
      get { return Id; }
      set { Id = value; }
    }
    public virtual String UNIT { get; set; }
    public virtual String ENG_SYS { get; set; }
    public virtual String ENG_SYS_CLIENT { get; set; }
    public virtual String CODE_COM_GRP { get; set; }
    public virtual String CODE_COM_GRP_CLIENT { get; set; }
    
    public virtual object GetPropertyValue(string propertyName)
    {
      switch (propertyName)
      {
        case "Id": return Id;
        case "TAG": return TAG;
        case "UNIT": return UNIT;
        case "ENG_SYS": return ENG_SYS;
        case "ENG_SYS_CLIENT": return ENG_SYS_CLIENT;
        case "CODE_COM_GRP": return CODE_COM_GRP;
        case "CODE_COM_GRP_CLIENT": return CODE_COM_GRP_CLIENT;
        default: throw new Exception("Property [" + propertyName + "] does not exist.");
      }
    }
    
    public virtual void SetPropertyValue(string propertyName, object value)
    {
      switch (propertyName)
      {
        case "Id":
          Id = Convert.ToString(value);
          break;
        case "TAG":
          TAG = Convert.ToString(value);
          break;
        case "UNIT":
          UNIT = Convert.ToString(value);
          break;
        case "ENG_SYS":
          ENG_SYS = Convert.ToString(value);
          break;
        case "ENG_SYS_CLIENT":
          ENG_SYS_CLIENT = Convert.ToString(value);
          break;
        case "CODE_COM_GRP":
          CODE_COM_GRP = Convert.ToString(value);
          break;
        case "CODE_COM_GRP_CLIENT":
          CODE_COM_GRP_CLIENT = Convert.ToString(value);
          break;
        default:
          throw new Exception("Property [" + propertyName + "] does not exist.");
      }
    }
    
    public virtual IList<IDataObject> GetRelatedObjects(string relatedObjectType)
    {
      switch (relatedObjectType)
      {
        default:
          throw new Exception("Related object [" + relatedObjectType + "] does not exist.");
      }
    }
  }
}
