/*
 * File: Scripts/AM/view/nhibernate/MultiSelectionGrid.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AM.view.nhibernate.MultiSelectionGrid', {
  extend: 'Ext.grid.Panel',
  alias: 'widget.multiselectiongrid',

  requires: [
    'AM.view.override.nhibernate.MultiSelectionGrid'
  ],

  frameHeader: false,
  header: false,
  enableColumnHide: false,
  enableColumnMove: false,
  enableColumnResize: false,
  sortableColumns: false,
  store: 'MultiStore',

  initComponent: function() {
    var me = this;

    Ext.applyIf(me, {
      columns: [
        {
          xtype: 'gridcolumn',
          draggable: false,
          sortable: false,
          dataIndex: 'DisplayField',
          flex: 1,
          menuText: false
        }
      ],
      viewConfig: {

      },
      selModel: Ext.create('Ext.selection.CheckboxModel', {
        showHeaderCheckbox: false
      })
    });

    me.callParent(arguments);
  },

  loadItems: function(items) {
    var me = this;
    var store = me.getStore();

    var records = [];

    Ext.each(items, function(item) {
      records.push({'DisplayField': item});
    });

    store.add(records);
  },

  selectItems: function(items) {
    var me = this;
    var store = me.getStore();
    var selectionModel = me.getSelectionModel();
    var view = me.getView();
    Ext.each(items, function(item) {
      var record = store.find('DisplayField', item);
      if(record) {
        selectionModel.select(record); 
      }           
    });

  },

  getSelectedItems: function() {
    var me = this;
    var store = me.getStore();
    var selectionModel = me.getSelectionModel();
    var items = [];

    Ext.each(selectionModel.getSelection(), function(record) {
      items.push(record.get('DisplayField'));
    });
  }

});