/*
 * File: Scripts/AM/view/mapping/ClassMapWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AM.view.mapping.ClassMapWindow', {
  extend: 'Ext.window.Window',
  alias: 'widget.classmapwindow',

  requires: [
    'AM.view.mapping.ClassMapForm'
  ],

  height: 280,
  width: 440,
  resizable: false,
  layout: {
    type: 'fit'
  },
  title: 'Add/Edit ClassMap',

  initComponent: function() {
    var me = this;

    me.addEvents(
      'save',
      'reset'
    );

    Ext.applyIf(me, {
      items: [
        {
          xtype: 'classmapform'
        }
      ]
    });

    me.callParent(arguments);
  }

});