//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.30 at 05:13:26 PM EDT 
//


package org.iringtools.directory;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExchangeDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExchangeDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sourceUri" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sourceAppName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sourceAppScope" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sourceGraphName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="targetUri" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="targetAppName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="targetAppScope" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="targetGraphName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hashAlgorithm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExchangeDefinition", propOrder = {
    "id",
    "sourceUri",
    "sourceAppName",
    "sourceAppScope",
    "sourceGraphName",
    "targetUri",
    "targetAppName",
    "targetAppScope",
    "targetGraphName",
    "hashAlgorithm"
})
@XmlRootElement(name = "exchangeDefinition")
public class ExchangeDefinition {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String sourceUri;
    @XmlElement(required = true)
    protected String sourceAppName;
    @XmlElement(required = true)
    protected String sourceAppScope;
    @XmlElement(required = true)
    protected String sourceGraphName;
    @XmlElement(required = true)
    protected String targetUri;
    @XmlElement(required = true)
    protected String targetAppName;
    @XmlElement(required = true)
    protected String targetAppScope;
    @XmlElement(required = true)
    protected String targetGraphName;
    @XmlElement(required = true)
    protected String hashAlgorithm;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the sourceUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceUri() {
        return sourceUri;
    }

    /**
     * Sets the value of the sourceUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceUri(String value) {
        this.sourceUri = value;
    }

    /**
     * Gets the value of the sourceAppName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceAppName() {
        return sourceAppName;
    }

    /**
     * Sets the value of the sourceAppName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceAppName(String value) {
        this.sourceAppName = value;
    }

    /**
     * Gets the value of the sourceAppScope property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceAppScope() {
        return sourceAppScope;
    }

    /**
     * Sets the value of the sourceAppScope property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceAppScope(String value) {
        this.sourceAppScope = value;
    }

    /**
     * Gets the value of the sourceGraphName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceGraphName() {
        return sourceGraphName;
    }

    /**
     * Sets the value of the sourceGraphName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceGraphName(String value) {
        this.sourceGraphName = value;
    }

    /**
     * Gets the value of the targetUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetUri() {
        return targetUri;
    }

    /**
     * Sets the value of the targetUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetUri(String value) {
        this.targetUri = value;
    }

    /**
     * Gets the value of the targetAppName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetAppName() {
        return targetAppName;
    }

    /**
     * Sets the value of the targetAppName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetAppName(String value) {
        this.targetAppName = value;
    }

    /**
     * Gets the value of the targetAppScope property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetAppScope() {
        return targetAppScope;
    }

    /**
     * Sets the value of the targetAppScope property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetAppScope(String value) {
        this.targetAppScope = value;
    }

    /**
     * Gets the value of the targetGraphName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetGraphName() {
        return targetGraphName;
    }

    /**
     * Sets the value of the targetGraphName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetGraphName(String value) {
        this.targetGraphName = value;
    }

    /**
     * Gets the value of the hashAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHashAlgorithm() {
        return hashAlgorithm;
    }

    /**
     * Sets the value of the hashAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHashAlgorithm(String value) {
        this.hashAlgorithm = value;
    }

}
