//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.30 at 05:13:26 PM EDT 
//


package org.iringtools.common.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.iringtools.adapter.dto.DataTransferObjects;


/**
 * <p>Java class for DxoRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DxoRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sourceDataTransferObjects" type="{http://iringtools.org/adapter/dto}DataTransferObjects"/>
 *         &lt;element name="targetDataTransferObjects" type="{http://iringtools.org/adapter/dto}DataTransferObjects"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DxoRequest", propOrder = {
    "sourceDataTransferObjects",
    "targetDataTransferObjects"
})
@XmlRootElement(name = "dxoRequest")
public class DxoRequest {

    @XmlElement(required = true)
    protected DataTransferObjects sourceDataTransferObjects;
    @XmlElement(required = true)
    protected DataTransferObjects targetDataTransferObjects;

    /**
     * Gets the value of the sourceDataTransferObjects property.
     * 
     * @return
     *     possible object is
     *     {@link DataTransferObjects }
     *     
     */
    public DataTransferObjects getSourceDataTransferObjects() {
        return sourceDataTransferObjects;
    }

    /**
     * Sets the value of the sourceDataTransferObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataTransferObjects }
     *     
     */
    public void setSourceDataTransferObjects(DataTransferObjects value) {
        this.sourceDataTransferObjects = value;
    }

    /**
     * Gets the value of the targetDataTransferObjects property.
     * 
     * @return
     *     possible object is
     *     {@link DataTransferObjects }
     *     
     */
    public DataTransferObjects getTargetDataTransferObjects() {
        return targetDataTransferObjects;
    }

    /**
     * Sets the value of the targetDataTransferObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataTransferObjects }
     *     
     */
    public void setTargetDataTransferObjects(DataTransferObjects value) {
        this.targetDataTransferObjects = value;
    }

}
