/*
 * File: Scripts/AM/view/nhibernate/SelectTablesForm.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AM.view.nhibernate.SelectTablesForm', {
  extend: 'Ext.form.Panel',
  alias: 'widget.selecttablesform',

  requires: [
    'AM.view.nhibernate.MultiSelectionGrid',
    'AM.view.nhibernate.MultiSelectComponentGrid'
  ],

  dirNode: '',
  width: 300,
  autoScroll: true,
  layout: {
    type: 'auto'
  },
  bodyStyle: 'background:#fff;padding:10px',
  title: 'Select Tables',

  initComponent: function() {
    var me = this;

    Ext.applyIf(me, {
      dockedItems: [
        {
          xtype: 'toolbar',
          dock: 'top',
          layout: {
            padding: 4,
            type: 'hbox'
          },
          items: [
            {
              xtype: 'tbspacer',
              width: 4
            },
            {
              xtype: 'button',
              action: 'applyobjects',
              iconCls: 'am-apply',
              text: 'Apply'
            },
            {
              xtype: 'tbspacer',
              width: 4
            },
            {
              xtype: 'button',
              action: 'resetobjects',
              iconCls: 'am-edit-clear',
              text: 'Reset'
            }
          ]
        }
      ],
      items: [
        {
          xtype: 'multiselectiongrid',
          hidden: true,
          itemId: 'tablesSelectionGrid',
          minHeight: 200
        },
        {
          xtype: 'multiselectcomponentgrid'
        },
        {
          xtype: 'hiddenfield',
          itemId: 'enableSummary',
          fieldLabel: 'Enable Summary:',
          labelWidth: 150,
          name: 'enableSummary',
          value: 'off'
        }
      ]
    });

    me.callParent(arguments);
  }

});