/*
 * File: Scripts/AM/view/nhibernate/DataKeyForm.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AM.view.nhibernate.DataKeyForm', {
  extend: 'Ext.form.Panel',
  alias: 'widget.datakeyform',

  bodyPadding: 10,
  bodyStyle: 'background:#fff;padding:10px',
  title: 'Configure Key',

  initComponent: function() {
    var me = this;

    Ext.applyIf(me, {
      defaults: {
        anchor: '100%',
        xtype: 'textfield',
        labelWidth: 160,
        allowBlank: false
      },
      items: [
        {
          xtype: 'textfield',
          anchor: '100%',
          fieldLabel: 'Column Name',
          labelWidth: 160,
          name: 'columnName',
          readOnly: true
        },
        {
          xtype: 'textfield',
          anchor: '100%',
          fieldLabel: 'Property Name (editable)',
          labelWidth: 160,
          name: 'propertyName',
          allowBlank: false,
          regex: /^[a-zA-Z_][a-zA-Z0-9_]*$/,
          regexText: '<b>Error</b></br>Invalid Value. A valid value should start with alphabet or "_", and follow by any number of "_", alphabet, or number characters'
        },
        {
          xtype: 'textfield',
          anchor: '100%',
          fieldLabel: 'Data Type',
          labelWidth: 160,
          name: 'dataType',
          readOnly: true
        },
        {
          xtype: 'textfield',
          anchor: '100%',
          fieldLabel: 'Data Length',
          labelWidth: 160,
          name: 'dataLength',
          readOnly: true
        },
        {
          xtype: 'checkboxfield',
          anchor: '100%',
          fieldLabel: 'Nullable',
          name: 'isNullable',
          readOnly: true
        },
        {
          xtype: 'checkboxfield',
          anchor: '100%',
          fieldLabel: 'Show on Index',
          name: 'showOnIndex'
        },
        {
          xtype: 'textfield',
          anchor: '100%',
          fieldLabel: 'Number of Decimals',
          labelWidth: 160,
          name: 'numberOfDecimals',
          readOnly: true
        },
        {
          xtype: 'checkboxfield',
          anchor: '100%',
          fieldLabel: 'Hidden',
          name: 'isHidden'
        },
        {
          xtype: 'textfield',
          anchor: '100%',
          hidden: true,
          fieldLabel: 'Key Type',
          labelWidth: 160,
          name: 'keyType',
          readOnly: true
        }
      ],
      dockedItems: [
        {
          xtype: 'toolbar',
          dock: 'top',
          layout: {
            padding: 4,
            type: 'hbox'
          },
          items: [
            {
              xtype: 'tbspacer',
              width: 4
            },
            {
              xtype: 'button',
              action: 'savekeyfield',
              iconCls: 'am-apply',
              text: 'Apply'
            },
            {
              xtype: 'tbspacer',
              width: 4
            },
            {
              xtype: 'button',
              action: 'resetkeyproperty',
              iconCls: 'am-edit-clear',
              text: 'Reset'
            }
          ]
        }
      ]
    });

    me.callParent(arguments);
  },

  setActiveRecord: function(record) {
    var me = this;
    if (record) {
      me.getForm().setValues(record);
    } else {
      me.getForm().reset();
    }
  }

});