/*
 * File: Scripts/AM/view/nhibernate/RelationPropertyGrid.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AM.view.nhibernate.RelationPropertyGrid', {
  extend: 'Ext.grid.Panel',
  alias: 'widget.relationPropertyGrid',

  itemId: 'relationPropertyGrid',
  store: 'PropertyMap',

  initComponent: function() {
    var me = this;

    Ext.applyIf(me, {
      dockedItems: [
        {
          xtype: 'toolbar',
          dock: 'top',
          items: [
            {
              xtype: 'button',
              iconCls: 'am-list-add',
              text: 'Add',
              listeners: {
                click: {
                  fn: me.onAddClick,
                  scope: me
                }
              }
            },
            {
              xtype: 'tbspacer',
              width: 4
            },
            {
              xtype: 'button',
              iconCls: 'am-list-remove',
              text: 'Remove',
              listeners: {
                click: {
                  fn: me.onRemoveClick,
                  scope: me
                }
              }
            }
          ]
        }
      ],
      columns: [
        {
          xtype: 'gridcolumn',
          dataIndex: 'property',
          text: 'Property'
        },
        {
          xtype: 'gridcolumn',
          dataIndex: 'relatedProperty',
          text: 'Related Property'
        }
      ]
    });

    me.callParent(arguments);
  },

  onAddClick: function(button, e, eOpts) {
    var me = this;

    var form = button.up('setrelationform');

    var treeNode = form.node;
    var propertyCmb = form.down('#propertyNameCmb');
    var mapPropertyCmb = form.down('#mapPropertyNameCmb');

    var message;

    if (!propertyCmb.getValue() || !mapPropertyCmb.getValue()) {
      message = 'Please select a property name and a mapping property.';
      showDialog(400, 100, 'Warning', message, Ext.Msg.OK, null);
      message = undefined;
      return;
    }

    var grid = form.down('relationPropertyGrid');
    var store = grid.getStore();

    var propertyName = propertyCmb.getValue().replace(/^\s*/, "").replace(/\s*$/, "");
    var mapProperty = mapPropertyCmb.getValue().replace(/^\s*/, "").replace(/\s*$/, "");

    var mapRecord = {'property': propertyName, 'relatedProperty': mapProperty};

    var propertErr = store.find('property', propertyName);
    var mapErr = store.find('relatedProperty', mapProperty);

    if (propertErr != -1) {
      message = 'Property [' + propertyName + '] already in a mapping!';
      showDialog(400, 100, 'Warning', message, Ext.Msg.OK, null);
      message = undefined;
      return; 
    }

    if (mapErr != -1) {
      message = 'Related Property [' + mapProperty + '] already in a mapping!';
      showDialog(400, 100, 'Warning', message, Ext.Msg.OK, null);
      message = undefined;
      return;
    }


    store.add(mapRecord);
  },

  onRemoveClick: function(button, e, eOpts) {

  }

});