/*
* File: Scripts/AM/view/directory/ApplicationForm.js
*
* This file was generated by Sencha Architect version 2.2.2.
* http://www.sencha.com/products/architect/
*
* This file requires use of the Ext JS 4.1.x library, under independent license.
* License of Sencha Architect does not include license for Ext JS 4.1.x. For more
* details see http://www.sencha.com/license or contact license@sencha.com.
*
* This file will be auto-generated each and everytime you save your project.
*
* Do NOT hand edit this file.
*/
Ext.define('AM.view.directory.NewJobForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.newjobform',
    border: false,
    bodyStyle: 'padding:10px 5px 0',
    url: 'directory/saveSchedularData',
    initComponent: function () {
        var me = this;

        me.initialConfig = Ext.apply({
            url: 'directory/saveSchedularData'
        }, me.initialConfig);

        var tempStore = Ext.create('Ext.data.Store', {
            fields: ['display'],
            listeners: {
                'load': function () {
                    var arr = Ext.getStore('DirectoryTreeStore').tree.root.childNodes;
                    Ext.each(arr, function (item, index) {
                        tempStore.insert(index, {
                            display: item.data.property["Display Name"]
                        });

                    })
                }

            }


        });



        Ext.applyIf(me, {

            items: [{
                xtype: 'fieldset',
                title: 'Job Info',
                layout: 'anchor',
                defaults: {
                    anchor: '100%'
                },
                items: [

                    {
                        xtype: 'container',
                        layout: 'hbox',
                        margin: '15 0 5 0',
                        items: [{
                            xtype: 'label',
                            name: 'cont',
                            text: 'Context',
                            margin: '4 61 0 0 ',
                            allowBlank: false
                        }, {

                            xtype: 'combobox',
                            itemId: 'scopecombo',
                            margin: '4 40 0 0 ',
                            labelWidth: 110,
                            name: 'displayName',
                            editable: false



                        }, {
                            xtype: 'label',
                            name: 'exch',
                            text: 'App',
                            margin: '4 40 0 0 ',
                            allowBlank: false
                        }, {
                            xtype: 'combobox',
                            name: 'applications',
                            itemId: 'appcombo',
                            store: 'apptempStore',
                            //                  forceSelection: true,
                            //                  triggerAction: 'all',
                            displayField: 'display',
                            valueField: 'display'

                        }]
                    }, {
                        xtype: 'container',
                        layout: 'hbox',
                        margin: '17 0 15 0',
                        items: [{
                            xtype: 'label',
                            name: 'exchurl',
                            text: 'DataObject',
                            margin: '4 42 0 0 ',
                            allowBlank: false
                        }, {
                            labelWidth: 110,
                            xtype: 'combobox',
                            name: 'dataobj',
                            allowBlank: false
                        }]
                    }
                ]
            }, {
                xtype: 'fieldset',
                title: '<b>Occurance</b>',
                border: 0,
                margin: '15 0 25 0 ',
                layout: 'anchor',
                defaults: {
                    anchor: '100%'
                },
                items: [{
                    xtype: 'container',
                    layout: 'hbox',
                    margin: '10 0 0 0',
                    items: [{
                        xtype: 'radio',
                        name: 'occrad',
                        margin: '0 3 0 0 ',
                        allowBlank: false
                    }, {
                        xtype: 'label',
                        name: 'labtex',
                        text: 'Daily',
                        margin: '4 50 0 0 ',
                        allowBlank: false
                    }, {
                        xtype: 'label',
                        name: 'st',
                        text: 'Start',
                        margin: '4 87 0 0 ',
                        allowBlank: false
                    }, {
                        xtype: 'datefield',
                        labelWidth: 110,
                        emptyText: 'Select Date',
                        name: 'startdat',
                        margin: '0 30 0 0 ',
                        allowBlank: false
                    }, {
                        xtype: 'timefield',
                        name: 'dailysttime',
                        minValue: '6:00 AM',
                        maxValue: '8:00 PM',
                        increment: 30,
                        emptyText: 'Select Time',
                        anchor: '100%'
                    }]
                }]

            }, {
                xtype: 'fieldset',
                border: 0,
                layout: 'anchor',
                defaults: {
                    anchor: '100%'
                },
                items: [{
                    xtype: 'container',
                    layout: 'hbox',
                    items: [{
                        xtype: 'radio',
                        name: 'occrad',
                        margin: '0 3 0 0 ',
                        allowBlank: false
                    }, {
                        xtype: 'label',
                        name: 'labtex',
                        text: 'Weekly',
                        margin: '4 40 0 0 ',
                        allowBlank: false
                    }, {
                        xtype: 'label',
                        name: 'wd',
                        text: 'WeekDays',
                        margin: '4 50 0 0 ',
                        allowBlank: false
                    }, {
                        xtype: 'combo',
                        labelWidth: 110,
                        emptyText: 'Options',
                        name: 'weeklycom',
                        margin: '0 30 0 0 ',
                        allowBlank: false
                    }, {
                        xtype: 'timefield',
                        name: 'wktimein',
                        minValue: '6:00 AM',
                        maxValue: '8:00 PM',
                        increment: 30,
                        emptyText: 'Select Time',
                        anchor: '100%'
                    }]
                }]

            }, {
                xtype: 'fieldset',
                border: 0,
                layout: 'anchor',
                defaults: {
                    anchor: '100%'
                },
                items: [{
                    xtype: 'container',
                    layout: 'hbox',
                    margin: '10 0 5 0',
                    items: [{
                        xtype: 'radio',
                        name: 'occrad',
                        margin: '0 3 0 0 ',
                        allowBlank: false
                    }, {
                        xtype: 'label',
                        name: 'labtex',
                        text: 'Monthly',
                        margin: '4 40 0 0 ',
                        allowBlank: false
                    }, {
                        xtype: 'label',
                        name: 'labtex',
                        text: 'End',
                        margin: '4 80 0 0 ',
                        allowBlank: false
                    }, {
                        xtype: 'radio',
                        name: 'occrad',
                        margin: '0 3 0 0 ',
                        allowBlank: false
                    }, {
                        xtype: 'label',
                        name: 'labtex',
                        text: 'No end Date',
                        margin: '4 98 0 0 ',
                        allowBlank: false
                    }, {
                        xtype: 'datefield',
                        labelWidth: 110,
                        emptyText: 'Select Date',
                        name: 'monthdate',
                        margin: '0 30 0 0 ',
                        allowBlank: false
                    }]
                }]



            }],
            dockedItems: [{
                xtype: 'toolbar',
                dock: 'bottom',
                items: [{
                    xtype: 'tbfill'
                }, {
                    xtype: 'button',
                    //action: 'saveNewJob',
                    handler: function (button, event) {
                        me.onSave();
                    },
                    text: 'Save'
                }, {
                    xtype: 'button',
                    handler: function (button, event) {
                        this.up('.window').close();
                        //me.down('newScopeDir').getForm().reset();
                        //me.destroy();


                    },
                    text: 'Cancel'
                }]
            }]
        });

        me.callParent(arguments);
    },


    onSave: function () {
        var me = this;
        var win = me.up('window');
        var endpointName = me.getForm().findField('displayName').getValue();
        var appls = me.getForm().findField('applications').getValue();
        var dataobj = me.getForm().findField('dataobj').getValue();
        var datest = me.getForm().findField('startdat').getValue();
        var dstime = me.getForm().findField('dailysttime').getValue();
        var wkdays = me.getForm().findField('weeklycom').getValue();
        var wktime = me.getForm().findField('wktimein').getValue();
        var mondat = me.getForm().findField('monthdate').getValue();

        me.getForm().submit({
            waitMsg: 'Saving Data...',
            success: function (response, request) {
                 //Ext.example.msg('Notification', 'Newjob saved successfully!');
                win.fireEvent('save', me);
               
                Ext.Msg.alert('Success', action.result.msg);
            },
            failure: function (response, request) {
                Ext.Msg.alert('Failed', action.result.msg);
            }
        });
    }




});